# github action

name: Build and Push Docker Image

on:
    push:
        branches:
            - main

env:
    DOCKER_REGISTRY: ghcr.io
    DOCKER_IMAGE_NAME: ismailoezcan/li
    DOCKER_IMAGE_TAG: latest

jobs:
    build-and-push-amd:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ubuntu-latest]
                arch: [amd64]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to GitHub Packages
              uses: docker/login-action@v1
              with:
                  registry: ${{ env.DOCKER_REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image for AMD
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}-amd64

    build-and-push-arm:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ubuntu-latest]
                arch: [arm64]
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Login to GitHub Packages
              uses: docker/login-action@v1
              with:
                  registry: ${{ env.DOCKER_REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image for ARM
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  tags: ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}-arm64
